#!/usr/bin/env bash
# Optional settings added by the 2026-09-05 review. Existing values are respected.
# Existing le8.sh CLI, resource limits and Top/All/None switches are unchanged.
export C2_MR_LD_R2="${C2_MR_LD_R2:-0.001}"
export C2_MR_MIN_F="${C2_MR_MIN_F:-10}"
export C2_MR_P="${C2_MR_P:-5e-8}"
export C2_DECOMP_FOLDS="${C2_DECOMP_FOLDS:-5}"
export C2_DANDELION_MULTIPLICITY="${C2_DANDELION_MULTIPLICITY:-BY}"
export C2_DANDELION_GENE_EVIDENCE="${C2_DANDELION_GENE_EVIDENCE:-unverified}"
export C2_DANDELION_GENE_SCOPE="${C2_DANDELION_GENE_SCOPE:-unknown}"
export LE8_TREATMENT_BASELINE_CONFIRMED="${LE8_TREATMENT_BASELINE_CONFIRMED:-FALSE}"
export C3_RUN_SUSIE="${C3_RUN_SUSIE:-FALSE}"
export C3_SUSIE_MAX_SNPS="${C3_SUSIE_MAX_SNPS:-5000}"
export C5_GENETIC_EVIDENCE_INDEPENDENT="${C5_GENETIC_EVIDENCE_INDEPENDENT:-FALSE}"
export C5_ASSAY_BUDGETS="${C5_ASSAY_BUDGETS:-3,5,10}"
export C5_REVIEW_HORIZONS="${C5_REVIEW_HORIZONS:-2,5,10}"
export C5_REVIEW_BOOT="${C5_REVIEW_BOOT:-100}"
