#!/usr/bin/env bash
set -euo pipefail

# MR-link-2 runner for the 5C CAD framework.
# The job TSV is generated by c2_cause.R.

conda_sh="${CONDA_SH:-/home/huangj/anaconda3/etc/profile.d/conda.sh}"
if [[ ! -r "$conda_sh" ]]; then
  echo "Conda initialization script not found: $conda_sh" >&2
  exit 1
fi
# shellcheck disable=SC1090
set +u
source "$conda_sh"
conda activate le8 || { echo "Failed to activate conda environment: le8" >&2; exit 1; }
set -u
cleanup_conda() { set +u; conda deactivate >/dev/null 2>&1 || true; }
trap cleanup_conda EXIT

if [[ -d /mnt/d/software/bin ]]; then
  export PATH="/mnt/d/software/bin:${PATH}"
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
prep_py="${script_dir}/c2_mr_link2.py"

jobs=""
cad_gwas=""
ref_bed="/mnt/d/refGen/1kg_phase3/ALL"
ref_pfile_dir="${MRLINK2_REF_PFILE_DIR:-/mnt/d/data.BIG/refGen/1kg/GRCH37/pfile}"
ref_pfile_pop="${MRLINK2_REF_POP:-EUR}"
mrlink2="${MRLINK2_SCRIPT:-${script_dir}/c2_mr_link2.py}"
outdir="c2_cause/link2"
python_bin="${PYTHON_BIN:-python3}"
verbose="${MRLINK2_VERBOSE:-1}"
p_threshold="${MRLINK2_P_THRESHOLD:-5e-8}"
region_padding="${MRLINK2_REGION_PADDING:-10000000}"
maf_threshold="${MRLINK2_MAF_THRESHOLD:-0.01}"
max_correlation="${MRLINK2_MAX_CORRELATION:-0.99}"
continue_analysis="${MRLINK2_CONTINUE:-true}"

usage() {
  cat <<'EOF'
Usage:
  bash f/c2_mr_link2.sh \
    --jobs c2_cause/link2/c2.link2.jobs.tsv \
    --cad-gwas /mnt/d/data.BIG/gwas/main/clean/cvd_cad/cvd_cad.gz \
    --reference-bed /mnt/d/refGen/1kg_phase3/ALL \
    --reference-pfile-dir /mnt/d/data.BIG/refGen/1kg/GRCH37/pfile \
    --reference-pop EUR \
    --mrlink2 f/c2_mr_link2.py \
    --outdir c2_cause/link2

The --jobs file is generated by c2_cause.R with columns:
  omics  trait  exposure  outcome  region
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --jobs) jobs="$2"; shift 2 ;;
    --cad-gwas) cad_gwas="$2"; shift 2 ;;
    --reference-bed|--ref-bed) ref_bed="$2"; shift 2 ;;
    --reference-pfile-dir|--ref-pfile-dir) ref_pfile_dir="$2"; shift 2 ;;
    --reference-pop|--ref-pop) ref_pfile_pop="$2"; shift 2 ;;
    --mrlink2) mrlink2="$2"; shift 2 ;;
    --outdir) outdir="$2"; shift 2 ;;
    --python) python_bin="$2"; shift 2 ;;
    --p-threshold) p_threshold="$2"; shift 2 ;;
    --region-padding) region_padding="$2"; shift 2 ;;
    --maf-threshold) maf_threshold="$2"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

mkdir -p "$outdir" "$outdir/prepared" "$outdir/logs" "$outdir/tmp" "$outdir/results"
status_file="$outdir/mrlink2.status.tsv"
all_file="$outdir/mrlink2.all.tsv"
complete_file="$outdir/mrlink2.complete"
if [[ -s "$complete_file" ]]; then
  echo "MR-link-2 already completed, skip MR-link-2 step: $status_file. Delete $complete_file to resume or delete $outdir to re-run."
  exit 0
fi
[[ -e "$all_file" ]] || : > "$all_file"
[[ -s "$status_file" ]] || printf "omics\ttrait\texposure\toutcome\tstatus\tout_prefix\tmessage\n" > "$status_file"

if [[ ! -s "$prep_py" ]]; then
  echo "Missing summary-stat standardizer: $prep_py" >&2
  exit 1
fi
if [[ -z "$jobs" || ! -s "$jobs" ]]; then
  echo "Missing job file: $jobs" >&2
  exit 1
fi
if [[ -z "$cad_gwas" || ! -s "$cad_gwas" ]]; then
  echo "Missing CAD GWAS file: $cad_gwas" >&2
  exit 1
fi
if [[ ! -s "$mrlink2" ]]; then
  echo "MR-link-2 script not found: $mrlink2" >&2
  exit 1
fi
have_ref_bed=true
for ext in bed bim fam; do
  [[ -s "${ref_bed}.${ext}" ]] || have_ref_bed=false
done
if [[ "$have_ref_bed" != "true" ]]; then
  if [[ -z "$ref_pfile_dir" || ! -d "$ref_pfile_dir" ]]; then
    echo "Missing reference bed prefix (${ref_bed}.bed/.bim/.fam) and pfile directory: $ref_pfile_dir" >&2
    exit 1
  fi
fi
if ! command -v plink >/dev/null 2>&1; then
  echo "plink 1.9 is required by MR-link-2. Install plink in WSL and ensure it is in PATH." >&2
  exit 1
fi
if ! "$python_bin" -c 'import bitarray, duckdb, numpy, pandas, pyarrow, scipy' >/dev/null 2>&1; then
  echo "MR-link-2 Python dependencies are unavailable via $python_bin." >&2
  echo "Synchronize the environment first: conda env update -n le8 -f environment.yml" >&2
  exit 1
fi

region_chrom() {
  local region="$1"
  local chrom="${region%%:*}"
  chrom="${chrom#chr}"
  echo "$chrom"
}

prepare_ref_bed() {
  local region="$1"
  if [[ "$have_ref_bed" == "true" ]]; then
    echo "$ref_bed"
    return 0
  fi
  local chrom
  chrom="$(region_chrom "$region")"
  local bed_prefix="${ref_pfile_dir}/${ref_pfile_pop}.chr${chrom}"
  if [[ -s "${bed_prefix}.bed" && -s "${bed_prefix}.bim" && -s "${bed_prefix}.fam" ]]; then
    echo "$bed_prefix"
    return 0
  fi
  local pfile_prefix="${ref_pfile_dir}/chr${chrom}"
  if [[ ! -s "${pfile_prefix}.pgen" || ! -s "${pfile_prefix}.pvar" || ! -s "${pfile_prefix}.psam" ]]; then
    pfile_prefix="${ref_pfile_dir}/${ref_pfile_pop}.chr${chrom}"
  fi
  if [[ ! -s "${pfile_prefix}.pgen" || ! -s "${pfile_prefix}.pvar" || ! -s "${pfile_prefix}.psam" ]]; then
    echo "Missing pfile prefix for chromosome ${chrom}: ${pfile_prefix}" >&2
    return 1
  fi
  local bed_dir="$outdir/reference_bed"
  mkdir -p "$bed_dir"
  local converted_bed_prefix="${bed_dir}/$(basename "$pfile_prefix")"
  if [[ ! -s "${converted_bed_prefix}.bed" || ! -s "${converted_bed_prefix}.bim" || ! -s "${converted_bed_prefix}.fam" ]]; then
    if ! command -v plink2 >/dev/null 2>&1; then
      echo "plink2 is required to convert ${pfile_prefix} to bed. Install plink2 or create ${pfile_prefix}.bed/.bim/.fam." >&2
      return 1
    fi
    plink2 --pfile "$pfile_prefix" --make-bed --out "$converted_bed_prefix" >/dev/null
  fi
  echo "$converted_bed_prefix"
}

standardize_sumstats() {
  local input="$1"
  local output="$2"
  local default_n="${3:-100000}"
  local region="${4:-}"
  if [[ -s "$output" ]]; then
    return 0
  fi
  if [[ -n "$region" ]]; then
    "$python_bin" "$prep_py" prepare "$input" "$output" "$default_n" "$region"
  else
    "$python_bin" "$prep_py" prepare "$input" "$output" "$default_n"
  fi
}

cad_std="$outdir/prepared/CAD.mrlink2.tsv.gz"
standardize_sumstats "$cad_gwas" "$cad_std" 100000

tail -n +2 "$jobs" | while IFS=$'\t' read -r omics trait exposure outcome region rest; do
  [[ -z "${trait:-}" ]] && continue
  outcome_file="${outcome:-$cad_gwas}"
  [[ -z "$outcome_file" ]] && outcome_file="$cad_gwas"
  if [[ ! -s "$exposure" ]]; then
    printf "%s\t%s\t%s\t%s\tnot_run\t\tmissing exposure file\n" "$omics" "$trait" "$exposure" "$outcome_file" >> "$status_file"
    continue
  fi
  safe_trait=$(echo "${omics}_${trait}" | sed 's/[^A-Za-z0-9_.-]/_/g')
  if awk -F '\t' -v om="$omics" -v tr="$trait" 'NR > 1 && $1 == om && $2 == tr && $5 == "ok" { found=1 } END { exit !found }' "$status_file"; then
    echo "MR-link-2/$safe_trait already completed, skip."
    continue
  fi
  exp_std="$outdir/prepared/${safe_trait}.exposure.mrlink2.tsv.gz"
  out_prefix="$outdir/results/${safe_trait}.mrlink2"
  log_file="$outdir/logs/${safe_trait}.log"
  err_file="$outdir/logs/${safe_trait}.err"
  if ! standardize_sumstats "$exposure" "$exp_std" 100000 "$region" >"$log_file.prepare" 2>"$err_file.prepare"; then
    printf "%s\t%s\t%s\t%s\tnot_run\t%s\tstandardization failed; see %s\n" "$omics" "$trait" "$exposure" "$outcome_file" "$out_prefix" "$err_file.prepare" >> "$status_file"
    continue
  fi
  ref_for_trait="$(prepare_ref_bed "$region" 2>>"$err_file.prepare" || true)"
  if [[ -z "$ref_for_trait" ]]; then
    printf "%s\t%s\t%s\t%s\tnot_run\t%s\treference conversion failed; see %s\n" "$omics" "$trait" "$exposure" "$outcome_file" "$out_prefix" "$err_file.prepare" >> "$status_file"
    continue
  fi
  cmd=("$python_bin" "$mrlink2" \
    --reference_bed "$ref_for_trait" \
    --sumstats_exposure "$exp_std" \
    --sumstats_outcome "$cad_std" \
    --out "$out_prefix" \
    --tmp "$outdir/tmp/${safe_trait}" \
    --p_threshold "$p_threshold" \
    --region_padding "$region_padding" \
    --maf_threshold "$maf_threshold" \
    --max_correlation "$max_correlation" \
    --verbose "$verbose")
  # The prot/met GWAS cleaning pipeline has already performed PLINK2 clumping,
  # and c2_cause.R records the selected lead-SNP locus in the jobs TSV. Pass
  # that locus through so MR-link-2 does not clump the exposure a second time.
  if [[ -n "${region:-}" ]]; then
    cmd+=(--prespecified_regions "$region")
  fi
  if [[ "$continue_analysis" == "true" || "$continue_analysis" == "TRUE" || "$continue_analysis" == "1" ]]; then
    cmd+=(--continue_analysis)
  fi
  if "${cmd[@]}" >"$log_file" 2>"$err_file"; then
    printf "%s\t%s\t%s\t%s\tok\t%s\tcompleted\n" "$omics" "$trait" "$exposure" "$outcome_file" "$out_prefix" >> "$status_file"
    found=0
    for f in "$out_prefix" "$out_prefix".*; do
      if [[ -s "$f" && "$f" != *.log && "$f" != *.err ]]; then
        if [[ $found -eq 0 && ! -s "$all_file" ]]; then
          awk -v OFS='\t' -v om="$omics" -v tr="$trait" 'NR==1{print "omics","trait",$0; next} NR>1{print om,tr,$0}' "$f" >> "$all_file" || true
        else
          awk -v OFS='\t' -v om="$omics" -v tr="$trait" 'NR>1{print om,tr,$0}' "$f" >> "$all_file" || true
        fi
        found=1
      fi
    done
  else
    printf "%s\t%s\t%s\t%s\tfailed\t%s\tMR-link-2 failed; see %s\n" "$omics" "$trait" "$exposure" "$outcome_file" "$out_prefix" "$err_file" >> "$status_file"
  fi
done

printf "completed\t%s\n" "$(date -Is)" > "$complete_file"

echo "MR-link-2 status: $status_file"
echo "MR-link-2 combined results: $all_file"
