#!/usr/bin/env bash
set -euo pipefail

# GPU-Coloc runner for the 5C CAD framework.
# The QTL manifest is generated by c3_coloc.R.

if [[ -n "${CONDA_SH:-}" ]]; then
  conda_sh="$CONDA_SH"
elif command -v conda >/dev/null 2>&1; then
  conda_sh="$(conda info --base)/etc/profile.d/conda.sh"
else
  conda_sh="/home/huangj/anaconda3/etc/profile.d/conda.sh"
fi
if [[ ! -r "$conda_sh" ]]; then
  echo "Conda initialization script not found: $conda_sh" >&2
  exit 1
fi
# shellcheck disable=SC1090
set +u
source "$conda_sh"
conda activate le8 || { echo "Failed to activate conda environment: le8" >&2; exit 1; }
set -u
cleanup_conda() { set +u; conda deactivate >/dev/null 2>&1 || true; }
trap cleanup_conda EXIT

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
prep_py="${script_dir}/c3_coloc_GPU.py"

manifest=""
cad_gwas=""
outdir="c3_coloc"
gpu_coloc_bin="${GPU_COLOC_BIN:-gpu-coloc}"
python_bin="${PYTHON_BIN:-python3}"
window_kb="${COLOC_WINDOW_KB:-500}"
p12="${GPU_COLOC_P12:-1e-5}"
h4="${GPU_COLOC_H4:-0.70}"
outcome_type="${GPU_COLOC_OUTCOME_TYPE:-cc}"

usage() {
  cat <<'EOF'
Usage:
  ./f/c3_coloc_GPU.sh \
    --qtl-manifest c3_coloc/qtl_cad_manifest.tsv \
    --cad-gwas /mnt/d/data.BIG/gwas/main/common/cvd_cad/gwas/cvd_cad.gz \
    --outdir c3_coloc \
    --outcome-type cc

The qtl manifest is generated by c3_coloc.R with columns:
  omics  trait  file  type  region
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --qtl-manifest) manifest="$2"; shift 2 ;;
    --cad-gwas) cad_gwas="$2"; shift 2 ;;
    --outdir) outdir="$2"; shift 2 ;;
    --gpu-coloc) gpu_coloc_bin="$2"; shift 2 ;;
    --python) python_bin="$2"; shift 2 ;;
    --window-kb) window_kb="$2"; shift 2 ;;
    --p12) p12="$2"; shift 2 ;;
    --H4|--h4) h4="$2"; shift 2 ;;
    --outcome-type) outcome_type="$2"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

mkdir -p "$outdir" "$outdir/qtl_signals" "$outdir/cad_signals" "$outdir/logs"
result_file="$outdir/gpu_coloc.results.tsv"
raw_result_file="$outdir/gpu_coloc.raw.tsv"
replace_run=false
case "${LE8_REPLACE:-FALSE}" in TRUE|true|1|yes|YES) replace_run=true ;; esac
if [[ -s "$result_file" && "$replace_run" != true ]]; then
  echo "GPU-coloc already exists, skip GPU-coloc step: $result_file. Delete this existing file (or $outdir) to re-run."
  exit 0
fi
if [[ "$replace_run" == true ]]; then
  rm -f "$result_file" "$raw_result_file"
  rm -rf "$outdir/qtl_signals" "$outdir/cad_signals" "$outdir/formatted_qtl" "$outdir/formatted_cad"
  mkdir -p "$outdir/qtl_signals" "$outdir/cad_signals"
fi

if [[ ! -s "$prep_py" ]]; then
  echo "Missing GPU-Coloc preparation script: $prep_py" >&2
  exit 1
fi
if [[ -z "$manifest" || ! -s "$manifest" ]]; then
  echo "Missing qtl manifest: $manifest" >&2
  exit 1
fi
if [[ -z "$cad_gwas" || ! -s "$cad_gwas" ]]; then
  echo "Missing CAD GWAS file: $cad_gwas" >&2
  exit 1
fi
if ! command -v "$gpu_coloc_bin" >/dev/null 2>&1; then
  echo "gpu-coloc command not found: $gpu_coloc_bin" >&2
  exit 1
fi

case "$outcome_type" in cc|quant) ;; *) echo "--outcome-type must be cc or quant" >&2; exit 1 ;; esac
"$python_bin" "$prep_py" "$manifest" "$cad_gwas" "$outdir" "$window_kb" "$outcome_type"

# A missing final result means this is not a valid cache hit.  Always format the
# just-created signal files so a previous failed or interrupted run cannot feed
# stale parquet matrices into a new analysis.
rm -rf "$outdir/formatted_qtl" "$outdir/formatted_cad"
"$gpu_coloc_bin" -f \
  --input "$outdir/qtl_signals" \
  --output "$outdir/formatted_qtl" \
  --input_summary "$outdir/qtl_summary.tsv" \
  --output_summary "$outdir/qtl_files_summary.tsv" \
  --input_type feather \
    >"$outdir/logs/gpu_coloc_format_qtl.log" 2>"$outdir/logs/gpu_coloc_format_qtl.err"

"$gpu_coloc_bin" -f \
  --input "$outdir/cad_signals" \
  --output "$outdir/formatted_cad" \
  --input_summary "$outdir/cad_summary.tsv" \
  --output_summary "$outdir/cad_files_summary.tsv" \
  --input_type feather \
    >"$outdir/logs/gpu_coloc_format_cad.log" 2>"$outdir/logs/gpu_coloc_format_cad.err"

rm -f "$raw_result_file"
"$gpu_coloc_bin" -r \
  --dir1 "$outdir/formatted_qtl" \
  --dir2 "$outdir/formatted_cad" \
  --results "$raw_result_file" \
  --p12 "$p12" \
  --H4 "$h4" \
  --get_NA_results \
  >"$outdir/logs/gpu_coloc_run.log" 2>"$outdir/logs/gpu_coloc_run.err"

# gpu-coloc tests every overlapping signal pair.  Keep the exact pair requested
# by each C3 manifest row and retain sub-threshold PP(H4) values for validation,
# instead of making "not returned" indistinguishable from "not tested".
"$python_bin" "$prep_py" filter-results "$raw_result_file" "$outdir/expected_pairs.tsv" "$result_file" "$h4"

echo "GPU-Coloc results: $outdir/gpu_coloc.results.tsv"
