#!/usr/bin/env bash
# Shared paths and defaults for Publication Fairness Index pipeline.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PFI_ROOT="${PFI_ROOT:-$SCRIPT_DIR}"

# Main roots.
ANALYSIS_ROOT="${ANALYSIS_ROOT:-/mnt/d/analysis/pfi}"
RAW_ROOT="${RAW_ROOT:-/mnt/g/pfi}"
DAT_DIR="${DAT_DIR:-$ANALYSIS_ROOT/dat}"
WORK_DIR="${WORK_DIR:-$ANALYSIS_ROOT/work}"
OUTPUT_DIR="${OUTPUT_DIR:-$ANALYSIS_ROOT/output}"
LOG_DIR="${LOG_DIR:-$ANALYSIS_ROOT/log}"
MODEL_DIR="${MODEL_DIR:-$ANALYSIS_ROOT/ml}"

# Large parquet/work areas.
PARQUET_DIR="${PARQUET_DIR:-$RAW_ROOT/parquet}"
PFI_WORK_PARQUET_DIR="${PFI_WORK_PARQUET_DIR:-$WORK_DIR/parquet}"
PFI_WORK_DB_DIR="${PFI_WORK_DB_DIR:-$WORK_DIR/duckdb}"
PFI_WORK_DUCKDB_TEMP_DIR="${PFI_WORK_DUCKDB_TEMP_DIR:-$WORK_DIR/duckdb_tmp}"

# Raw archives.
PUBMED_BASELINE_DIR="${PUBMED_BASELINE_DIR:-$RAW_ROOT/pubmed/baseline}"
PUBMED_UPDATE_DIR="${PUBMED_UPDATE_DIR:-$RAW_ROOT/pubmed/updatefiles}"
PMC_OA_RAW_DIR="${PMC_OA_RAW_DIR:-$RAW_ROOT/pmc_oa_bulk_xml}"

# Core pipeline outputs.
PFI_ARTICLES_MASTER="${PFI_ARTICLES_MASTER:-$PFI_WORK_PARQUET_DIR/articles_master}"
PFI_BLINDED_TEXT="${PFI_BLINDED_TEXT:-$PFI_WORK_PARQUET_DIR/blinded_text}"
PFI_ARTICLE_FEATURES="${PFI_ARTICLE_FEATURES:-$PFI_WORK_PARQUET_DIR/article_features}"
PFI_JOURNAL_RANK_REAL="${PFI_JOURNAL_RANK_REAL:-$PFI_ROOT/journal_rank_real.csv}"
PFI_JOURNAL_RANK_NORMALIZED="${PFI_JOURNAL_RANK_NORMALIZED:-$DAT_DIR/journal_rank_normalized.parquet}"

PFI_PAPER_SCORE_REVIEW_CSV="${PFI_PAPER_SCORE_REVIEW_CSV:-$DAT_DIR/paper_score_review_${PFI_REVIEW_ROWS:-1000}_blinded.csv}"
PFI_PAPER_SCORE_REVIEW_XLSX="${PFI_PAPER_SCORE_REVIEW_XLSX:-$DAT_DIR/paper_score_review_${PFI_REVIEW_ROWS:-1000}_blinded.xlsx}"
PFI_PAPER_SCORE_REVIEW_KEY="${PFI_PAPER_SCORE_REVIEW_KEY:-$DAT_DIR/paper_score_review_${PFI_REVIEW_ROWS:-1000}_key.parquet}"
PFI_PAPER_SCORE_REVIEW_SCORED="${PFI_PAPER_SCORE_REVIEW_SCORED:-$DAT_DIR/paper_score_review_${PFI_REVIEW_ROWS:-1000}_scored.csv}"
PFI_PAPER_SCORE_REVIEW_PSEUDO="${PFI_PAPER_SCORE_REVIEW_PSEUDO:-$DAT_DIR/paper_score_review_${PFI_REVIEW_ROWS:-1000}_pseudo_scored.csv}"
PFI_PAPER_SCORE_REVIEW_PSEUDO_AUDIT="${PFI_PAPER_SCORE_REVIEW_PSEUDO_AUDIT:-$DAT_DIR/paper_score_review_${PFI_REVIEW_ROWS:-1000}_pseudo_scored_audit.csv}"
PFI_PAPER_SCORE_REVIEW_SUMMARY="${PFI_PAPER_SCORE_REVIEW_SUMMARY:-$DAT_DIR/paper_score_review_${PFI_REVIEW_ROWS:-1000}_sampling_summary.csv}"

PFI_TRAINING_DATASET="${PFI_TRAINING_DATASET:-$DAT_DIR/training_dataset.parquet}"
PFI_PUBMEDBERT_PREDICTIONS="${PFI_PUBMEDBERT_PREDICTIONS:-$DAT_DIR/pubmedbert_predictions.parquet}"
PFI_FAIRNESS_RESULTS_PARQUET="${PFI_FAIRNESS_RESULTS_PARQUET:-$DAT_DIR/fairness_results.parquet}"
PFI_FAIRNESS_RESULTS_CSV="${PFI_FAIRNESS_RESULTS_CSV:-$DAT_DIR/fairness_results.csv}"
PFI_ANALYSIS_DATA_DIR="${PFI_ANALYSIS_DATA_DIR:-$DAT_DIR/analysis}"

# Defaults.
MIN_YEAR="${MIN_YEAR:-2000}"
N_JOBS="${N_JOBS:-4}"
PFI_TEST_MODE="${PFI_TEST_MODE:-0}"
PFI_FULL_TEXT_ONLY="${PFI_FULL_TEXT_ONLY:-1}"
PFI_BLINDED_FULL_TEXT_ONLY="${PFI_BLINDED_FULL_TEXT_ONLY:-1}"
PFI_RESULTS_FULL_TEXT_ONLY="${PFI_RESULTS_FULL_TEXT_ONLY:-1}"
PFI_REVIEW_ROWS="${PFI_REVIEW_ROWS:-1000}"
PFI_REVIEW_SEED="${PFI_REVIEW_SEED:-1}"
PFI_PRED_SAMPLE_ROWS="${PFI_PRED_SAMPLE_ROWS:-1000000}"
PFI_PRED_SAMPLE_SEED="${PFI_PRED_SAMPLE_SEED:-1}"
PFI_MAX_TRAIN_ROWS="${PFI_MAX_TRAIN_ROWS:-1000}"
PFI_MIN_TEXT_CHARS="${PFI_MIN_TEXT_CHARS:-500}"
FULL_TEXT_MAX_CHARS="${FULL_TEXT_MAX_CHARS:-400000}"

PFI_PYTHON_BIN="${PFI_PYTHON_BIN:-python}"
PFI_RSCRIPT_BIN="${PFI_RSCRIPT_BIN:-Rscript}"
PFI_DUCKDB_THREADS="${PFI_DUCKDB_THREADS:-4}"

# PubMedBERT/BiomedBERT.
PFI_PUBMEDBERT_MODEL="${PFI_PUBMEDBERT_MODEL:-/mnt/d/data.BIG/AI_model_files/pubmedbert_abstract_fulltext}"
PFI_PUBMEDBERT_FALLBACK="${PFI_PUBMEDBERT_FALLBACK:-microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext}"
PFI_BERT_EPOCHS="${PFI_BERT_EPOCHS:-5}"
PFI_BERT_BATCH_SIZE="${PFI_BERT_BATCH_SIZE:-8}"
PFI_BERT_GRAD_ACCUM="${PFI_BERT_GRAD_ACCUM:-4}"
PFI_BERT_MAX_LENGTH="${PFI_BERT_MAX_LENGTH:-512}"
PFI_BERT_LR="${PFI_BERT_LR:-2e-5}"
PFI_BERT_FP16="${PFI_BERT_FP16:-0}"
PFI_ALLOW_CPU_FULL_PRED="${PFI_ALLOW_CPU_FULL_PRED:-0}"

mkdir -p "$DAT_DIR" "$WORK_DIR" "$OUTPUT_DIR" "$LOG_DIR" "$MODEL_DIR" "$PFI_WORK_PARQUET_DIR" "$PFI_WORK_DB_DIR" "$PFI_WORK_DUCKDB_TEMP_DIR"

check_raw_mounts() {
  if [[ ! -d "$(dirname "$RAW_ROOT")" ]]; then
    echo "ERROR: raw-data mount is not available: $(dirname "$RAW_ROOT")" >&2
    exit 1
  fi
  mkdir -p "$RAW_ROOT" "$PUBMED_BASELINE_DIR" "$PUBMED_UPDATE_DIR" "$PMC_OA_RAW_DIR" "$PARQUET_DIR"
}
