# UK Biobank birth-order / birth-season phenome-wide analyses
# Steps: order, season
# Designed to consume PHEDIR/Rdata/all.rds generated by phe.R.

suppressPackageStartupMessages({
  library(data.table)
  library(dplyr)
  library(ggplot2)
  library(survival)
  library(PheWAS)
})

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 🚩 Paths and step dispatcher
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dir0 <- Sys.getenv("DIR0", unset = ifelse(Sys.info()[["sysname"]] == "Windows", "D:/", "/mnt/d"))
indir <- Sys.getenv("PHEDIR", unset = file.path(dir0, "data/ukb/phe"))
outdir <- Sys.getenv("UKB_OUT", unset = file.path(dir0, "analysis/birth"))
gen_dir <- Sys.getenv("GEN_DIR", unset = file.path(dir0, "data/ukb/gen"))
if (!dir.exists(outdir)) dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

step_order <- c("order", "season")
run_steps <- trimws(unlist(strsplit(Sys.getenv("RUN_STEPS", unset = "order,season"), ",|;|\\s+")))
run_steps <- run_steps[nzchar(run_steps)]
bad_steps <- setdiff(run_steps, step_order)
if (length(bad_steps)) stop("Unknown RUN_STEPS: ", paste(bad_steps, collapse = ", "))
run_step <- function(step) step %in% run_steps
run_if <- function(step, expr) {
  if (run_step(step)) {
    cat("\n========== RUN STEP:", step, "==========\n")
    eval(substitute(expr), envir = parent.frame())
    cat("========== DONE STEP:", step, "==========\n")
  } else cat("Skip step:", step, "\n")
}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 🚩 User-tunable parameters
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
env_int <- function(name, default) {
  x <- suppressWarnings(as.integer(Sys.getenv(name, unset = as.character(default))))
  if (!is.finite(x) || x < 1) default else x
}
env_chr <- function(name, default) Sys.getenv(name, unset = default)

sib_cap <- env_int("SIB_CAP", 10L)
min_cases_order <- env_int("MIN_CASES_ORDER", env_int("MIN_CASES", 500L))
min_cases_season <- env_int("MIN_CASES_SEASON", env_int("MIN_CASES", 500L))
min_discordant_within <- env_int("MIN_DISCORDANT_WITHIN", 100L)
# Forked workers inherit the very large all.rds/PheWAS.rds objects and glm.fit
# allocates additional working matrices.  A parallel default can therefore
# exhaust WSL memory even on machines with tens of GiB available.
n_jobs <- env_int("N_JOBS", 1L)
primary_model <- env_chr("PRIMARY_MODEL", "m2")
phenome_source <- tolower(env_chr("PHENOME_SOURCE", "auto"))
monthly_top <- env_int("MONTHLY_TOP", 30L)
strata_top <- env_int("STRATA_TOP", 20L)
run_within_mode <- tolower(env_chr("RUN_WITHIN", "auto"))
pheno_map_file <- env_chr("PHENO_MAP", "")
if (!nzchar(pheno_map_file)) pheno_map_file <- file.path(indir, "common", "birth.phenome.lst")

if (!primary_model %in% c("m1", "m2", "m3")) stop("PRIMARY_MODEL must be m1/m2/m3")
if (!phenome_source %in% c("auto", "phewas", "fod")) stop("PHENOME_SOURCE must be auto/phewas/fod")
if (!run_within_mode %in% c("auto", "0", "1")) stop("RUN_WITHIN must be auto/0/1")

cat("SIB_CAP=", sib_cap,
    " MIN_CASES_ORDER=", min_cases_order,
    " MIN_CASES_SEASON=", min_cases_season,
    " MIN_DISCORDANT_WITHIN=", min_discordant_within,
    " N_JOBS=", n_jobs,
    " PRIMARY_MODEL=", primary_model, "\n", sep = "")

all_file <- file.path(indir, "Rdata", "all.rds")
if (!file.exists(all_file)) stop("Cannot find ", all_file)
dat <- readRDS(all_file)
if (!is.data.frame(dat)) dat <- as.data.frame(dat)
if (!"eid" %in% names(dat)) stop("all.rds is missing eid")
dat$eid <- as.character(dat$eid)
if (anyDuplicated(dat$eid)) stop("all.rds contains duplicated eid")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 🚩 Helpers
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
num_col <- function(d, nm) {
  if (!nm %in% names(d)) return(rep(NA_real_, nrow(d)))
  suppressWarnings(as.numeric(as.character(d[[nm]])))
}
fac_col <- function(d, nm) {
  if (!nm %in% names(d)) return(factor(rep(NA_character_, nrow(d))))
  factor(d[[nm]])
}
as_date2 <- function(x) {
  if (inherits(x, "Date")) return(x)
  if (inherits(x, "IDate")) return(as.Date(x))
  if (inherits(x, "POSIXt")) return(as.Date(x))
  if (is.character(x)) return(suppressWarnings(as.Date(x)))
  z <- suppressWarnings(as.numeric(unclass(x)))
  z[!is.finite(z)] <- NA_real_
  as.Date(z, origin = "1970-01-01")
}
scale_safe <- function(x) {
  x <- suppressWarnings(as.numeric(x))
  s <- sd(x, na.rm = TRUE); m <- mean(x, na.rm = TRUE)
  if (!is.finite(s) || s <= 0) return(rep(NA_real_, length(x)))
  (x - m) / s
}
quantile_group <- function(x, n = 3L, prefix = "Q") {
  x <- suppressWarnings(as.numeric(x))
  q <- unique(quantile(x, probs = seq(0, 1, length.out = n + 1), na.rm = TRUE, names = FALSE))
  if (length(q) < 3) return(factor(rep(NA_character_, length(x))))
  k <- cut(x, breaks = q, include.lowest = TRUE, labels = FALSE)
  factor(ifelse(is.na(k), NA, paste0(prefix, k)), levels = paste0(prefix, seq_len(length(q) - 1L)))
}
parallel_lapply <- function(X, FUN) {
  if (n_jobs > 1L && .Platform$OS.type != "windows") {
    parallel::mclapply(X, FUN, mc.cores = n_jobs, mc.preschedule = TRUE)
  } else lapply(X, FUN)
}
write_tsv <- function(x, filename) {
  data.table::fwrite(as.data.frame(x), file.path(outdir, filename), sep = "\t", na = "NA", quote = FALSE)
}
write_xlsx_if_available <- function(filename, sheets) {
  if (!requireNamespace("openxlsx", quietly = TRUE)) {
    message("openxlsx not installed; skipped ", filename)
    return(invisible(FALSE))
  }
  wb <- openxlsx::createWorkbook()
  for (nm in names(sheets)) {
    sh <- substr(gsub("[:\\/?*\\[\\]]", "_", nm), 1, 31)
    openxlsx::addWorksheet(wb, sh)
    openxlsx::writeData(wb, sh, as.data.frame(sheets[[nm]]))
    openxlsx::freezePane(wb, sh, firstRow = TRUE)
  }
  openxlsx::saveWorkbook(wb, file.path(outdir, filename), overwrite = TRUE)
  invisible(TRUE)
}

# Category-based PheWAS Manhattan plot. `colors` are recycled across disease
# categories; `pcts` maps positive and negative effects, respectively.
make_phewas_plot <- function(res, title, colors = c("gray", "lightblue"), pcts = c(17, 19)) {
  if (!requireNamespace("PheWAS", quietly = TRUE)) {
    stop("Package 'PheWAS' is required for the PheWAS plot")
  }
  if (length(colors) < 1L || anyNA(colors)) stop("colors must contain at least one valid color")
  if (length(pcts) != 2L || anyNA(pcts)) stop("pcts must contain positive and negative point shapes")
  d <- as.data.frame(res)
  d <- d[is.finite(d$p) & is.finite(d$OR), , drop = FALSE]
  if (!nrow(d)) stop("No finite PheWAS results to plot")
  d$phenotype <- as.character(d$phenotype)

  # Determine how many disease groups the PheWAS package will draw, then
  # replace its multi-colour palette with the requested alternating colours.
  info <- suppressMessages(PheWAS::addPhecodeInfo(d, groupnums = TRUE, groupcolors = TRUE))
  n_groups <- length(unique(info$color[order(info$groupnum)]))
  palette <- rep(colors, length.out = n_groups)
  p <- suppressMessages(PheWAS::phewasManhattan(
    d,
    annotate.phenotype.description = TRUE,
    title = title,
    OR.direction = TRUE,
    color.palette = palette,
    size.x.labels = 14,
    size.y.labels = 14
  )) +
    ggplot2::scale_shape_manual(
      name = "Effect",
      values = c(`FALSE` = pcts[[2]], `TRUE` = pcts[[1]]),
      breaks = c(FALSE, TRUE), labels = c("Negative", "Positive")
    ) +
    ggplot2::theme(text = ggplot2::element_text(size = 12))
  p
}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 🚩 Birth / sibling variables and QC
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
prepare_birth_data <- function(d) {
  req <- c("cnt_brother", "cnt_sister", "cnt_older", "birth_year", "birth_month")
  miss <- setdiff(req, names(d))
  if (length(miss)) warning("Missing variable(s): ", paste(miss, collapse = ", "))

  bro <- num_col(d, "cnt_brother")
  sis <- num_col(d, "cnt_sister")
  old <- num_col(d, "cnt_older")
  n_sib <- ifelse(!is.na(bro) & !is.na(sis), bro + sis, NA_real_)

  impossible_neg <- (!is.na(bro) & bro < 0) | (!is.na(sis) & sis < 0) | (!is.na(old) & old < 0)
  over_component_cap <- (!is.na(bro) & bro > sib_cap) | (!is.na(sis) & sis > sib_cap) | (!is.na(old) & old > sib_cap)
  over_total_cap <- !is.na(n_sib) & n_sib > sib_cap
  older_gt_all_sibs <- !is.na(old) & !is.na(n_sib) & old > n_sib
  sib_qc_bad <- impossible_neg | over_component_cap | over_total_cap | older_gt_all_sibs

  d$cnt_brother_raw <- bro
  d$cnt_sister_raw <- sis
  d$cnt_older_raw <- old
  d$cnt_brother_cap <- ifelse(is.na(bro), NA, pmin(pmax(bro, 0), sib_cap))
  d$cnt_sister_cap <- ifelse(is.na(sis), NA, pmin(pmax(sis, 0), sib_cap))
  d$cnt_older_cap <- ifelse(is.na(old), NA, pmin(pmax(old, 0), sib_cap))
  d$n_sib_raw <- n_sib
  d$n_sib_cap <- ifelse(is.na(n_sib), NA, pmin(pmax(n_sib, 0), sib_cap))
  d$family_children <- ifelse(!sib_qc_bad & !is.na(n_sib), n_sib + 1, NA_real_)
  d$birth_order <- ifelse(!sib_qc_bad & !is.na(old) & !is.na(n_sib), old + 1, NA_real_)
  d$sib_qc_bad <- sib_qc_bad

  # Article-like primary cohort: a true two-child sibship from the participant's report.
  d$two_child <- !sib_qc_bad & !is.na(n_sib) & n_sib == 1 & old %in% c(0, 1)
  d$second_born <- ifelse(d$two_child, as.integer(old == 1), NA_integer_)
  d$order2_f <- factor(ifelse(d$second_born == 0, "first-born",
                             ifelse(d$second_born == 1, "second-born", NA_character_)),
                       levels = c("first-born", "second-born"))

  by <- num_col(d, "birth_year")
  bm <- num_col(d, "birth_month")
  d$birth_year_num <- by
  d$birth_cohort5_f <- factor(ifelse(is.finite(by), floor(by / 5) * 5, NA))
  d$birth_month_num <- ifelse(bm %in% 1:12, bm, NA_real_)
  d$birth_month_f <- factor(d$birth_month_num, levels = 1:12, labels = month.abb)
  d$season4_f <- factor(case_when(
    d$birth_month_num %in% c(12, 1, 2) ~ "Winter",
    d$birth_month_num %in% 3:5 ~ "Spring",
    d$birth_month_num %in% 6:8 ~ "Summer",
    d$birth_month_num %in% 9:11 ~ "Autumn",
    TRUE ~ NA_character_
  ), levels = c("Winter", "Spring", "Summer", "Autumn"))
  theta <- 2 * pi * (d$birth_month_num - 1) / 12
  d$month_sin <- sin(theta)
  d$month_cos <- cos(theta)

  d$sex_f <- if ("sex.f" %in% names(d)) factor(d$sex.f) else fac_col(d, "sex")
  d$ethnic_f <- if ("ethnic.c" %in% names(d)) factor(d$ethnic.c) else fac_col(d, "ethnicity")
  d$center_f <- fac_col(d, "center")

  d$tdi_birth_z <- scale_safe(num_col(d, "tdi.birth"))
  d$birth_east_z <- scale_safe(num_col(d, "birth_east"))
  d$birth_north_z <- scale_safe(num_col(d, "birth_north"))
  d$birth_east_z2 <- d$birth_east_z^2
  d$birth_north_z2 <- d$birth_north_z^2
  d$birth_en_int <- d$birth_east_z * d$birth_north_z
  d$tdi_z <- scale_safe(num_col(d, "tdi"))
  d$age_z <- scale_safe(num_col(d, "age"))
  d$age_z2 <- d$age_z^2

  d$tdi_birth_tertile <- quantile_group(num_col(d, "tdi.birth"), 3, "T")
  d$birth_north_tertile <- quantile_group(num_col(d, "birth_north"), 3, "N")

  if (all(c("date_attend", "date_follow_end") %in% names(d))) {
    fu <- as.numeric(as_date2(d$date_follow_end) - as_date2(d$date_attend)) / 365.25
    fu[!is.finite(fu) | fu < 0] <- NA_real_
  } else fu <- rep(NA_real_, nrow(d))
  d$followup_z <- scale_safe(fu)
  d$followup_z2 <- d$followup_z^2
  d
}

dat <- prepare_birth_data(dat)

# Covariate hierarchy. Current TDI/centre are deliberately sensitivity terms rather
# than primary childhood-exposure covariates.
model_covars <- list(
  m1 = c("sex_f", "age_z", "age_z2", "birth_cohort5_f", "ethnic_f", "followup_z", "followup_z2"),
  m2 = c("sex_f", "age_z", "age_z2", "birth_cohort5_f", "ethnic_f", "followup_z", "followup_z2",
         "tdi_birth_z", "birth_east_z", "birth_north_z", "birth_east_z2", "birth_north_z2", "birth_en_int"),
  m3 = c("sex_f", "age_z", "age_z2", "birth_cohort5_f", "ethnic_f", "followup_z", "followup_z2",
         "tdi_birth_z", "birth_east_z", "birth_north_z", "birth_east_z2", "birth_north_z2", "birth_en_int",
         "tdi_z", "center_f")
)

usable_covars <- function(d, idx, vars) {
  vars <- intersect(vars, names(d))
  keep <- vapply(vars, function(v) {
    z <- d[[v]][idx]
    z <- z[!is.na(z)]
    if (!length(z)) return(FALSE)
    length(unique(as.character(z))) >= 2
  }, logical(1))
  vars[keep]
}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 🚩 Phenome provider
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
read_pheno_map <- function() {
  if (!file.exists(pheno_map_file)) return(NULL)
  mp <- tryCatch(fread(pheno_map_file, sep = "\t", header = TRUE, fill = TRUE), error = function(e) NULL)
  if (is.null(mp) || !nrow(mp)) return(NULL)
  nms <- tolower(names(mp))
  pcol <- which(nms %in% c("phenotype", "phecode", "trait", "id"))[1]
  if (is.na(pcol)) pcol <- 1L
  lcol <- which(nms %in% c("label", "description", "name"))[1]
  ccol <- which(nms %in% c("category", "group", "chapter"))[1]
  data.frame(
    phenotype = as.character(mp[[pcol]]),
    label = if (!is.na(lcol)) as.character(mp[[lcol]]) else as.character(mp[[pcol]]),
    category = if (!is.na(ccol)) as.character(mp[[ccol]]) else NA_character_,
    stringsAsFactors = FALSE
  )
}

build_phenome_provider <- function(d) {
  phewas_file <- file.path(indir, "Rdata", "PheWAS.rds")
  src <- phenome_source
  if (src == "auto") src <- if (file.exists(phewas_file)) "phewas" else "fod"

  if (src == "phewas") {
    if (!file.exists(phewas_file)) stop("PHENOME_SOURCE=phewas but missing ", phewas_file)
    ph <- readRDS(phewas_file)
    if (!is.data.frame(ph)) ph <- as.data.frame(ph, check.names = FALSE)
    idcol <- intersect(c("eid", "id", "IID"), names(ph))[1]
    if (is.na(idcol)) idcol <- names(ph)[1]
    ids <- as.character(ph[[idcol]])
    idx <- match(d$eid, ids)
    phenos <- setdiff(names(ph), idcol)
    get_y <- function(p) {
      out <- integer(nrow(d))
      hit <- !is.na(idx)
      v <- ph[[p]][idx[hit]]
      out[hit] <- as.integer(!is.na(v) & suppressWarnings(as.numeric(v)) > 0)
      out
    }
    meta <- data.frame(phenotype = phenos, label = phenos, category = "phecode", stringsAsFactors = FALSE)
  } else {
    fod_cols <- grep("^fod_(icd10|icd9|srd|gp|ref)_", names(d), value = TRUE)
    if (!length(fod_cols)) stop("No FOD phenotype columns found in all.rds")
    suffix <- sub("^fod_(icd10|icd9|srd|gp|ref)_", "", fod_cols)
    groups <- split(fod_cols, suffix)
    phenos <- names(groups)
    get_y <- function(p) {
      cc <- groups[[p]]
      if (length(cc) == 1L) return(as.integer(!is.na(d[[cc]])))
      as.integer(Reduce(`|`, lapply(cc, function(z) !is.na(d[[z]]))))
    }
    cat0 <- ifelse(grepl("^cvd_", phenos), "cardiovascular",
                   ifelse(grepl("^(t2dm|dm|met)", phenos), "metabolic",
                          sub("_.*$", "", phenos)))
    meta <- data.frame(phenotype = phenos, label = phenos, category = cat0, stringsAsFactors = FALSE)
  }

  mp <- read_pheno_map()
  if (!is.null(mp)) {
    hit <- match(meta$phenotype, mp$phenotype)
    ok_label <- !is.na(hit) & !is.na(mp$label[hit]) & nzchar(mp$label[hit])
    ok_cat <- !is.na(hit) & !is.na(mp$category[hit]) & nzchar(mp$category[hit])
    meta$label[ok_label] <- mp$label[hit[ok_label]]
    meta$category[ok_cat] <- mp$category[hit[ok_cat]]
    # If a map is supplied, treat it as an analysis whitelist.
    keep <- meta$phenotype %in% mp$phenotype
    meta <- meta[keep, , drop = FALSE]
    phenos <- meta$phenotype
  }

  cat("Phenome source: ", src, "; phenotypes: ", length(phenos), "\n", sep = "")
  list(source = src, phenotypes = phenos, meta = meta, get_y = get_y)
}

provider <- build_phenome_provider(dat)
meta <- provider$meta

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 🚩 Fast fixed-design logistic regression
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make_design <- function(d, idx, exposure, covars) {
  covars <- usable_covars(d, idx, covars)
  vars <- c(exposure, covars)
  cc <- idx & complete.cases(d[, vars, drop = FALSE])
  dd <- droplevels(d[cc, vars, drop = FALSE])
  if (!nrow(dd) || length(unique(dd[[exposure]])) < 2) return(NULL)
  f <- reformulate(c(exposure, covars))
  X <- model.matrix(f, data = dd)
  j <- match(exposure, colnames(X))
  if (is.na(j)) stop("Exposure column missing from design: ", exposure)
  list(rows = which(cc), X = X, exposure_col = j, covars = covars, n = nrow(X))
}

fit_matrix <- function(X, y) {
  fit <- tryCatch(suppressWarnings(glm.fit(x = X, y = y, family = binomial())), error = function(e) NULL)
  if (is.null(fit)) return(NULL)
  p <- ncol(X); r <- fit$rank
  se <- rep(NA_real_, p)
  if (r > 0L) {
    piv <- fit$qr$pivot[seq_len(r)]
    R <- qr.R(fit$qr)[seq_len(r), seq_len(r), drop = FALSE]
    vc <- tryCatch(chol2inv(R), error = function(e) NULL)
    if (!is.null(vc)) se[piv] <- sqrt(pmax(diag(vc), 0))
  }
  list(beta = fit$coefficients, se = se, deviance = fit$deviance,
       converged = isTRUE(fit$converged), n = length(y), rank = r)
}

fit_exposure_design <- function(y, design, min_cases) {
  if (is.null(design)) return(NULL)
  yy <- y[design$rows]
  cases <- sum(yy == 1L, na.rm = TRUE); controls <- sum(yy == 0L, na.rm = TRUE)
  if (cases < min_cases || controls < min_cases) return(NULL)
  fit <- fit_matrix(design$X, yy)
  if (is.null(fit)) return(NULL)
  j <- design$exposure_col
  b <- fit$beta[j]; s <- fit$se[j]
  if (!is.finite(b) || !is.finite(s) || s <= 0) return(NULL)
  p <- 2 * pnorm(abs(b / s), lower.tail = FALSE)
  data.frame(n = fit$n, cases = cases, controls = controls,
             beta = b, se = s, OR = exp(b), lo = exp(b - 1.96 * s), hi = exp(b + 1.96 * s),
             p = p, converged = fit$converged, stringsAsFactors = FALSE)
}

add_multiplicity <- function(res, group = "model") {
  if (!nrow(res)) return(res)
  res %>% group_by(.data[[group]]) %>% mutate(
    n_tests = sum(is.finite(p)),
    p_bonf = pmin(p * n_tests, 1),
    q_fdr = p.adjust(p, method = "BH"),
    bonf_sig = p_bonf < 0.05,
    fdr_sig = q_fdr < 0.05
  ) %>% ungroup()
}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 🚩 ORDER
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run_if("order", {
  idx_order <- dat$two_child %in% TRUE
  if (sum(idx_order) < 100) stop("Too few exactly-two-child participants after QC: ", sum(idx_order))

  designs <- lapply(names(model_covars), function(m) make_design(dat, idx_order, "second_born", model_covars[[m]]))
  names(designs) <- names(model_covars)
  if (is.null(designs[[primary_model]])) stop("Primary order design is empty: ", primary_model)

  cohort <- data.frame(
    metric = c("all_participants", "cnt_older_observed", "any_sibling_QC_failure", "valid_sibship",
               "two_child_primary", "first_born_two_child", "second_born_two_child",
               paste0("complete_", names(designs))),
    value = c(nrow(dat), sum(!is.na(dat$cnt_older_raw)), sum(dat$sib_qc_bad %in% TRUE),
              sum(!dat$sib_qc_bad & !is.na(dat$birth_order)), sum(idx_order),
              sum(dat$second_born == 0, na.rm = TRUE), sum(dat$second_born == 1, na.rm = TRUE),
              vapply(designs, function(z) if (is.null(z)) 0L else z$n, integer(1))),
    stringsAsFactors = FALSE
  )
  write_tsv(cohort, "order.cohort.tsv")

  dist_order <- dat %>% filter(!sib_qc_bad, !is.na(n_sib_raw), !is.na(birth_order)) %>%
    count(n_sib_raw, birth_order, name = "N") %>% arrange(n_sib_raw, birth_order)
  write_tsv(dist_order, "order.distribution.tsv")

  primary_rows <- designs[[primary_model]]$rows
  work <- parallel_lapply(provider$phenotypes, function(ph) {
    y <- provider$get_y(ph)
    if (sum(y[primary_rows] == 1L) < min_cases_order) return(NULL)
    out <- lapply(names(designs), function(m) {
      z <- fit_exposure_design(y, designs[[m]], min_cases_order)
      if (is.null(z)) return(NULL)
      z$phenotype <- ph; z$model <- m; z
    })
    bind_rows(out)
  })
  res <- bind_rows(work)
  if (!nrow(res)) stop("No order phenotype passed MIN_CASES_ORDER=", min_cases_order)
  res <- left_join(res, meta, by = "phenotype") %>%
    add_multiplicity("model") %>%
    mutate(direction = ifelse(OR < 1, "first-born excess", "second-born excess")) %>%
    arrange(model, p)
  write_tsv(res, "order.phewas.tsv")

  pr <- res %>% filter(model == primary_model, is.finite(p)) %>% arrange(p)
  if (!nrow(pr)) stop("No primary-model order results")

  # Stratified sensitivity analyses: top signals only, to avoid multiplying thousands of fits.
  top_ph <- head(pr$phenotype, strata_top)
  strata_out <- list()
  kk <- 0L
  for (sv in c("tdi_birth_tertile", "birth_north_tertile")) {
    levs <- levels(dat[[sv]])
    for (lv in levs) {
      idx_s <- idx_order & dat[[sv]] == lv
      des <- make_design(dat, idx_s, "second_born", model_covars[[primary_model]])
      if (is.null(des)) next
      for (ph in top_ph) {
        z <- fit_exposure_design(provider$get_y(ph), des, max(30L, floor(min_cases_order / 4)))
        if (is.null(z)) next
        kk <- kk + 1L
        z$phenotype <- ph; z$strata_var <- sv; z$stratum <- lv; z$model <- primary_model
        strata_out[[kk]] <- z
      }
    }
  }
  strata_res <- bind_rows(strata_out)
  if (nrow(strata_res)) {
    strata_res <- left_join(strata_res, meta, by = "phenotype") %>%
      group_by(strata_var, stratum) %>% mutate(q_fdr = p.adjust(p, "BH")) %>% ungroup()
    write_tsv(strata_res, "order.strata.tsv")
  }

  # Optional genetic full-sibling within-family validation using UKB kinship data.
  within_res <- data.frame()
  rel_file <- file.path(gen_dir, "typ", "ukb_rel.dat")
  do_within <- run_within_mode == "1" || (run_within_mode == "auto" && file.exists(rel_file))
  if (do_within) {
    if (!file.exists(rel_file)) {
      warning("RUN_WITHIN=1 but missing ", rel_file)
    } else {
      cat("Within-family: reading ", rel_file, "\n", sep = "")
      rel <- fread(rel_file, header = TRUE, showProgress = FALSE)
      pick <- function(pattern) names(rel)[grep(pattern, names(rel), ignore.case = TRUE)][1]
      id1c <- pick("^ID1$|id1"); id2c <- pick("^ID2$|id2")
      kinc <- pick("kinship"); ibs0c <- pick("ibs0")
      if (any(is.na(c(id1c, id2c, kinc, ibs0c)))) {
        warning("Cannot identify ID1/ID2/Kinship/IBS0 columns in ukb_rel.dat; skipped within-family analysis")
      } else {
        rr <- data.frame(
          id1 = as.character(rel[[id1c]]), id2 = as.character(rel[[id2c]]),
          kin = suppressWarnings(as.numeric(rel[[kinc]])), ibs0 = suppressWarnings(as.numeric(rel[[ibs0c]])),
          stringsAsFactors = FALSE
        ) %>% filter(is.finite(kin), is.finite(ibs0), kin > 0.1767, kin < 0.354, ibs0 > 0.0012)
        i1 <- match(rr$id1, dat$eid); i2 <- match(rr$id2, dat$eid)
        keep <- !is.na(i1) & !is.na(i2) & dat$two_child[i1] & dat$two_child[i2] &
          dat$second_born[i1] != dat$second_born[i2]
        rr <- rr[keep, , drop = FALSE]
        if (nrow(rr)) {
          # Retain clean disjoint pairs only; larger/ambiguous sibling components are excluded.
          tt <- table(c(rr$id1, rr$id2)); ambig <- names(tt)[tt > 1]
          rr <- rr[!rr$id1 %in% ambig & !rr$id2 %in% ambig, , drop = FALSE]
        }
        cat("Eligible disjoint genetic full-sibling pairs: ", nrow(rr), "\n", sep = "")
        if (nrow(rr) >= 20) {
          rr$pair_id <- paste0("pair", seq_len(nrow(rr)))
          long <- bind_rows(
            data.frame(pair_id = rr$pair_id, eid = rr$id1),
            data.frame(pair_id = rr$pair_id, eid = rr$id2)
          )
          long$row_id <- match(long$eid, dat$eid)
          long$second_born <- dat$second_born[long$row_id]
          long$age <- num_col(dat, "age")[long$row_id]
          long$sex_f <- dat$sex_f[long$row_id]
          long <- long %>% filter(!is.na(second_born), !is.na(age), !is.na(sex_f))

          within_work <- parallel_lapply(pr$phenotype, function(ph) {
            yy <- provider$get_y(ph)[long$row_id]
            dd <- long; dd$y <- yy
            ps <- dd %>% group_by(pair_id) %>% summarise(s = sum(y), n = n(), .groups = "drop")
            good_pairs <- ps$pair_id[ps$n == 2 & ps$s == 1]
            ndisc <- length(good_pairs)
            if (ndisc < min_discordant_within) return(NULL)
            dx <- dd %>% filter(pair_id %in% good_pairs)
            fit <- tryCatch(survival::clogit(y ~ second_born + age + sex_f + strata(pair_id), data = dx),
                            error = function(e) NULL)
            if (is.null(fit)) return(NULL)
            sm <- summary(fit)$coefficients
            if (!"second_born" %in% rownames(sm)) return(NULL)
            b <- sm["second_born", "coef"]
            se <- sm["second_born", "se(coef)"]
            p <- sm["second_born", "Pr(>|z|)"]
            data.frame(phenotype = ph, n_pairs = nrow(rr), discordant_pairs = ndisc,
                       beta = b, se = se, OR = exp(b), lo = exp(b - 1.96 * se), hi = exp(b + 1.96 * se), p = p)
          })
          within_res <- bind_rows(within_work)
          if (nrow(within_res)) {
            within_res <- left_join(within_res, meta, by = "phenotype") %>%
              mutate(n_tests = n(), p_bonf = pmin(p * n_tests, 1), q_fdr = p.adjust(p, "BH")) %>% arrange(p)
            write_tsv(within_res, "order.within_family.tsv")
          }
        }
      }
    }
  } else message("Within-family analysis skipped (RUN_WITHIN=0 or kinship file absent).")

  # Figures and their corresponding result workbooks.
  p1 <- make_phewas_plot(pr, "Birth order across the UK Biobank phenome",
                         colors = c("gray", "lightblue"), pcts = c(17, 19))
  ggsave(file.path(outdir, "order.Fig1.phewas.png"), p1, width = 14, height = 8, dpi = 300, bg = "white")
  write_xlsx_if_available("order.Fig1.xlsx", list(phewas = pr))

  top20 <- pr %>% slice_head(n = 20) %>% mutate(label = factor(label, levels = rev(label)))
  p2 <- ggplot(top20, aes(x = OR, y = label)) +
    geom_vline(xintercept = 1, linetype = 2) + geom_errorbarh(aes(xmin = lo, xmax = hi), height = 0.18) +
    geom_point() + scale_x_log10() +
    labs(x = "OR (second-born vs first-born), log scale", y = NULL,
         title = "Top birth-order associations") + theme_bw(base_size = 11)
  ggsave(file.path(outdir, "order.Fig2.forest.png"), p2, width = 9, height = 8, dpi = 300, bg = "white")
  write_xlsx_if_available("order.Fig2.xlsx", list(forest = as.data.frame(top20)))

  if (nrow(within_res)) {
    cmp <- inner_join(pr %>% select(phenotype, OR_between = OR, p_between = p),
                      within_res %>% select(phenotype, OR_within = OR, p_within = p), by = "phenotype")
    if (nrow(cmp) >= 3) {
      r0 <- suppressWarnings(cor(log(cmp$OR_between), log(cmp$OR_within), use = "complete.obs"))
      p3 <- ggplot(cmp, aes(x = log(OR_between), y = log(OR_within))) + geom_point() +
        geom_abline(slope = 1, intercept = 0, linetype = 2) +
        labs(x = "Between-family log(OR)", y = "Within-family log(OR)",
             title = "Between-family vs genetic-sibling estimates",
             subtitle = paste0("Pearson r = ", sprintf("%.2f", r0))) + theme_bw(base_size = 12)
      ggsave(file.path(outdir, "order.Fig3.within_vs_between.png"), p3, width = 7, height = 7, dpi = 300, bg = "white")
      write_xlsx_if_available("order.Fig3.xlsx", list(within_vs_between = cmp))
    }
  }

})

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 🚩 SEASON
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make_season_design <- function(d, idx, covars) {
  covars <- usable_covars(d, idx, covars)
  vars <- c("month_sin", "month_cos", covars)
  cc <- idx & complete.cases(d[, vars, drop = FALSE])
  dd <- droplevels(d[cc, vars, drop = FALSE])
  if (!nrow(dd)) return(NULL)
  f0 <- reformulate(covars)
  f1 <- reformulate(c("month_sin", "month_cos", covars))
  X0 <- model.matrix(f0, data = dd)
  X1 <- model.matrix(f1, data = dd)
  list(rows = which(cc), X0 = X0, X1 = X1,
       sin_col = match("month_sin", colnames(X1)), cos_col = match("month_cos", colnames(X1)),
       covars = covars, n = nrow(dd))
}

fit_season_design <- function(y, design, min_cases) {
  if (is.null(design)) return(NULL)
  yy <- y[design$rows]
  cases <- sum(yy == 1L); controls <- sum(yy == 0L)
  if (cases < min_cases || controls < min_cases) return(NULL)
  f0 <- fit_matrix(design$X0, yy); f1 <- fit_matrix(design$X1, yy)
  if (is.null(f0) || is.null(f1)) return(NULL)
  bsin <- f1$beta[design$sin_col]; bcos <- f1$beta[design$cos_col]
  if (!is.finite(bsin) || !is.finite(bcos)) return(NULL)
  stat <- max(0, f0$deviance - f1$deviance)
  p <- pchisq(stat, df = 2, lower.tail = FALSE)
  amp <- sqrt(bsin^2 + bcos^2)
  phi <- atan2(bsin, bcos)
  if (phi < 0) phi <- phi + 2 * pi
  peak_cont <- 1 + 12 * phi / (2 * pi)
  peak_month <- ((round(peak_cont) - 1L) %% 12L) + 1L
  data.frame(n = f1$n, cases = cases, controls = controls,
             beta_sin = bsin, beta_cos = bcos, amplitude = amp,
             peak_month = peak_month, peak_month_name = month.abb[peak_month],
             OR_peak_vs_trough = exp(2 * amp), LRT = stat, p = p,
             converged = f0$converged & f1$converged, stringsAsFactors = FALSE)
}

make_month_design <- function(d, idx, covars) {
  covars <- usable_covars(d, idx, covars)
  vars <- c("birth_month_f", covars)
  cc <- idx & complete.cases(d[, vars, drop = FALSE])
  dd <- droplevels(d[cc, vars, drop = FALSE])
  f <- reformulate(c("birth_month_f", covars))
  X <- model.matrix(f, data = dd)
  list(rows = which(cc), X = X, covars = covars, n = nrow(dd), coef_names = colnames(X))
}

extract_monthly <- function(y, design, phenotype) {
  yy <- y[design$rows]
  fit <- fit_matrix(design$X, yy)
  if (is.null(fit)) return(NULL)
  out <- data.frame(phenotype = phenotype, month = 1L, month_name = month.abb[1],
                    beta = 0, se = 0, OR = 1, lo = 1, hi = 1, p = NA_real_, n = fit$n)
  for (m in 2:12) {
    nm <- paste0("birth_month_f", month.abb[m])
    j <- match(nm, design$coef_names)
    if (is.na(j)) next
    b <- fit$beta[j]; s <- fit$se[j]
    if (!is.finite(b) || !is.finite(s)) next
    out <- bind_rows(out, data.frame(phenotype = phenotype, month = m, month_name = month.abb[m],
                                     beta = b, se = s, OR = exp(b), lo = exp(b - 1.96 * s), hi = exp(b + 1.96 * s),
                                     p = 2 * pnorm(abs(b / s), lower.tail = FALSE), n = fit$n))
  }
  out
}

run_if("season", {
  idx_season <- !is.na(dat$birth_month_num) & !is.na(dat$birth_year_num)
  if (sum(idx_season) < 1000) stop("Too few participants with birth month/year")

  season_designs <- lapply(names(model_covars), function(m) make_season_design(dat, idx_season, model_covars[[m]]))
  names(season_designs) <- names(model_covars)
  if (is.null(season_designs[[primary_model]])) stop("Primary season design is empty: ", primary_model)

  month_counts <- dat[idx_season, , drop = FALSE] %>% count(birth_month_num, birth_month_f, name = "N") %>% arrange(birth_month_num)
  cohort <- data.frame(
    metric = c("all_participants", "birth_month_observed", paste0("complete_", names(season_designs))),
    value = c(nrow(dat), sum(idx_season), vapply(season_designs, function(z) if (is.null(z)) 0L else z$n, integer(1))),
    stringsAsFactors = FALSE
  )
  write_tsv(cohort, "season.cohort.tsv")
  write_tsv(month_counts, "season.month_counts.tsv")

  primary_rows <- season_designs[[primary_model]]$rows
  work <- parallel_lapply(provider$phenotypes, function(ph) {
    y <- provider$get_y(ph)
    if (sum(y[primary_rows] == 1L) < min_cases_season) return(NULL)
    out <- lapply(names(season_designs), function(m) {
      z <- fit_season_design(y, season_designs[[m]], min_cases_season)
      if (is.null(z)) return(NULL)
      z$phenotype <- ph; z$model <- m; z
    })
    bind_rows(out)
  })
  res <- bind_rows(work)
  if (!nrow(res)) stop("No season phenotype passed MIN_CASES_SEASON=", min_cases_season)
  res <- left_join(res, meta, by = "phenotype") %>% add_multiplicity("model") %>% arrange(model, p)
  write_tsv(res, "season.phewas.tsv")

  pr <- res %>% filter(model == primary_model, is.finite(p)) %>% arrange(p)
  top_ph <- head(pr$phenotype, monthly_top)
  month_design <- make_month_design(dat, idx_season, model_covars[[primary_model]])
  monthly_res <- bind_rows(parallel_lapply(top_ph, function(ph) extract_monthly(provider$get_y(ph), month_design, ph)))
  if (nrow(monthly_res)) {
    monthly_res <- left_join(monthly_res, meta, by = "phenotype")
    write_tsv(monthly_res, "season.monthly_OR.top.tsv")
  }

  # TDI-at-birth and northing strata: top signals only.
  strat_ph <- head(pr$phenotype, strata_top)
  strata_out <- list(); kk <- 0L
  for (sv in c("tdi_birth_tertile", "birth_north_tertile")) {
    for (lv in levels(dat[[sv]])) {
      idx_s <- idx_season & dat[[sv]] == lv
      des <- make_season_design(dat, idx_s, model_covars[[primary_model]])
      if (is.null(des)) next
      for (ph in strat_ph) {
        z <- fit_season_design(provider$get_y(ph), des, max(50L, floor(min_cases_season / 4)))
        if (is.null(z)) next
        kk <- kk + 1L
        z$phenotype <- ph; z$strata_var <- sv; z$stratum <- lv; z$model <- primary_model
        strata_out[[kk]] <- z
      }
    }
  }
  strata_res <- bind_rows(strata_out)
  if (nrow(strata_res)) {
    strata_res <- left_join(strata_res, meta, by = "phenotype") %>%
      group_by(strata_var, stratum) %>% mutate(q_fdr = p.adjust(p, "BH")) %>% ungroup()
    write_tsv(strata_res, "season.strata.tsv")
  }

  # Seasonal amplitude is non-negative, so all cyclic effects use the positive shape.
  pr_plot <- pr %>% mutate(OR = OR_peak_vs_trough)
  p1 <- make_phewas_plot(pr_plot, "Month of birth across the UK Biobank phenome",
                         colors = c("gray", "lightblue"), pcts = c(17, 19))
  ggsave(file.path(outdir, "season.Fig1.phewas.png"), p1, width = 14, height = 8, dpi = 300, bg = "white")
  write_xlsx_if_available("season.Fig1.xlsx", list(phewas = pr))

  if (nrow(monthly_res)) {
    show_ph <- head(pr$phenotype, min(6L, length(top_ph)))
    mm <- monthly_res %>% filter(phenotype %in% show_ph) %>%
      mutate(label = factor(label, levels = unique(pr$label[match(show_ph, pr$phenotype)])))
    p2 <- ggplot(mm, aes(x = month, y = OR, group = phenotype)) +
      geom_hline(yintercept = 1, linetype = 2) + geom_line() + geom_point() +
      geom_ribbon(aes(ymin = lo, ymax = hi), alpha = 0.12, linewidth = 0) +
      scale_x_continuous(breaks = 1:12, labels = month.abb) + facet_wrap(~ label, scales = "free_y") +
      labs(x = "Month of birth", y = "OR vs January",
           title = "Monthly odds ratios for top seasonal phenotypes") + theme_bw(base_size = 10)
    ggsave(file.path(outdir, "season.Fig2.monthly.png"), p2, width = 11, height = 8, dpi = 300, bg = "white")
    write_xlsx_if_available("season.Fig2.xlsx", list(monthly = monthly_res))
  }

})
