name: grid-argneedle
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.10
  - numpy<2
  - scipy
  - pandas
  - h5py
  - scikit-learn
  - tskit=0.6.4
  - msprime=1.3.4
  - fastcluster=1.2.6
  - click
  - newick
  - demes
  - psutil
  - cython
  - pybind11
  - scikit-build-core
  - numba
  - cmake
  - make
  - compilers
  - boost-cpp
  - gsl
  - eigen
  - pkg-config
  - git
  - gzip
  - pigz
  - zstd
  - plink2
  - bgenix
  - r-base>=4.2
  - r-data.table
  - r-ggplot2
  - r-patchwork
  - r-openxlsx
  - r-proc
  - r-matrix
  - r-r.utils
  - pip
