name: gu
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - git
  - cmake>=3.14
  - make
  - cxx-compiler
  - bcftools>=1.19
  - htslib>=1.19
  - bedtools
  - samtools
  - plink2
  - bgenix>=1.1.7
  - sqlite
  - parallel
  - jq
  - wget
  - curl
  - phyml
  - numpy>=1.26
  - pandas>=2.1
  - scipy
  - matplotlib>=3.8
  - openpyxl
  - pysam
  - cyvcf2
  - pybedtools
  - zarr<3
  - r-base>=4.3
  - r-data.table
  - r-ape
  - r-pegas
  - r-writexl
  - r-shiny
  - r-bslib
  - r-plotly
  - r-dt
  - r-dbi
  - r-rsqlite
  - r-htmltools
  - r-jsonlite
  - r-scales
  - scikit-learn
  - h5py
  - tqdm
  - scikit-allel
  - opencv
  - pip:
      - transformers==4.46.3
      - einops
      - ninja
      - packaging
      - bio2zarr>=0.1.7
      - tskit>=1.0,<2
      - tszip>=0.2
      - tsinfer>=0.5.1
      - tsdate>=0.2.7
