# A persistent IGV header is shared by both navigation pages.
ui <- bslib::page_navbar(title = "GWAS block browser", id = "nav", selected = "overview",
  theme = bslib::bs_theme(version = 5, bootswatch = "flatly", base_font = "system-ui"),
  header = tagList(
    tags$head(tags$title("GWAS block browser"), tags$link(rel = "icon", href = "data:,"),
      tags$link(rel = "stylesheet", href = "bplot_assets/bplot.css?v=2"),
      tags$script(src = "bplot_assets/vendor/igv-3.0.0.min.js"),
      tags$script(src = "bplot_assets/bplot.js?v=2")),
    div(class = "browser-card",
      div(id = "igv-status", role = "alert", style = "display:none"),
      div(id = "igv", style = "min-height:160px"))),
  bslib::nav_panel("Overview", value = "overview",
    div(class = "plot-card", div(class = "card-heading controls-heading", h4("GWAS"),
      div(class = "build-control", selectInput("build", NULL,
        choices = c("GRCh 37" = "37", "GRCh 38" = "38"), selected = opt$grch, width = "126px", selectize = FALSE)),
      div(id = "chromosomes", role = "group", `aria-label` = "Chromosome",
        lapply(c("All", as.character(1:22), "X"), function(chr) tags$button(type = "button",
          class = if (chr == "All") "chr-btn active" else "chr-btn", `data-chr` = chr, chr)))),
      div(class = "toolbar", textInput("region", NULL, placeholder = "chr1:10,000,000-12,000,000", width = "280px"),
        actionButton("go", "定位"), actionButton("zoom_in", "＋ 放大"), actionButton("zoom_out", "－ 缩小"),
        actionButton("reset", "重置视野"), checkboxInput("blocks", "LD block boundaries", TRUE)),
      div(class = "view-status", textOutput("status")), uiOutput("panel"),
      div(class = "plot-footer", "拖框或滚轮缩放；单击位点定位，双击 block 进入 Blockview。",
        tags$br(), "shown 是实际显示点数；in input region 是输入文件在视野内的位点数。仅显示存在的 [race].[grch].bed 边界。"))),
  bslib::nav_panel("Blockview", value = "blockview",
    div(class = "plot-card", div(class = "card-heading", h4("Block View"), textOutput("block_title", inline = TRUE)),
      div(class = "toolbar", actionButton("block_home", "所选 block ＋ 相邻 blocks"),
        actionButton("block_in", "＋ 放大"), actionButton("block_out", "－ 缩小"),
        actionButton("back", "返回 Overview")),
      div(class = "view-status", textOutput("block_status")), uiOutput("block_panel")),
    div(class = "plot-card ld-card", div(class = "card-heading", h4("LD view"), span("EUR · AFR · EAS · SAS · AMR")),
      div(class = "view-status", textOutput("ld_status")), uiOutput("ld_panel"),
      div(class = "plot-footer", "颜色表示 r²，所有人群使用同一组 SNP 和基因组坐标。白色表示参考数据缺失或 HDF5 未提供的跨块 LD。",
        tags$br(), "所选 BED block 与 HDF5 的 blk_* 编号相互独立。GRCh38 的参考 SNP 坐标通过 liftOver 转换。"))),
  footer = NULL)
